# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Star Wars Info' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Star Wars Info
  pod 'Alamofire'
  pod 'RealmSwift'
  pod 'RxRealm'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Unbox'
  pod 'Then'
  pod 'Reachability'
  pod 'Kingfisher'
  pod 'RxRealmDataSources'
  pod 'RxDataSources', '~> 3.0'
  pod 'Action'
  pod 'NSObject+Rx'
  pod 'SwiftyJSON', '~> 4.0'

  target 'Star Wars InfoTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxTest'
    pod 'RxBlocking'
  end

  target 'Star Wars InfoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
